# Dependencies
<body class="theme-base-0b">
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            Paulina Cakalli
tagline:          'Data Scientist'
description:      'Personal blog where I post my research.'
url:              http://paulinacakalli.github.io/
baseurl:          /

author:
  name:           'Paulina Cakalli'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

</body>
